/**
 * Created by Administrator on 2016/11/3.
 */
angular.module('validationExample',[])
.directive('ensureUnique',function($http){
    return{
        require:'ngModel',
        link:function(scope,element,attrs,c){
            scope.$watch(attrs.ngModel,function(){
                $http({
                    method:'get',
                    url:'',
                    data:{filed:attrs.ensureUnique,valud:scope.ngModel}
                }).success(function(data,status,headers,cfg){
                    c.$setValidity('unique',data.isUnique);
                }).error(function(data,status,headers,cfg){
                    c.$setValidity('unique',false);
                })
            });
        }
    }
});